---
- name: "[WORDPRESS] - Update cache"
  apt:
    update_cache: yes
  become: yes

- name: "[WORDPRESS] - Install apt-utils if missing"
  apt:
    name: apt-utils
    state: present
  become: yes
  ignore_errors: yes

- name: "[WORDPRESS] - Install LAMP"
  apt:
    name: "{{ item }}"
    state: present
  become: yes
  with_items: "{{ packages_name }}"
  ignore_errors: yes

- name: "[WORDPRESS] - Start Apache2 and MySQL services"
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  become: yes

- name: "[WORDPRESS] - Display service status"
  debug:
    msg: "The service {{ item.item }} is {{ item.state }}"
  with_items: "{{ service_status.results }}"
