---
- name: "[WORDPRESS] - Install packages"
  include_tasks: install_packages.yml

- name: "[WORDPRESS] - Install database"
  include_tasks: install_db.yml

- name: "[WORDPRESS] - Install wordpress"
  include_tasks: install_wordpress.yml
